# .pre-commit-config.yaml
exclude: |
  (?x)^(
      frontend/node_modules/|
      backend/venv/| # If you use venv instead of pipenv for some reason
      backend/.venv/| # For pipenv's default .venv location
      .git/
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the latest stable version
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0 # Use the latest stable version
    hooks:
      - id: flake8
        # --- CHANGES START HERE ---
        language: python # Change from system to python
        types: [python]
        additional_dependencies: ["flake8==6.0.0"] # Specify the version
        # --- CHANGES END HERE ---

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0 # Use the latest stable version
    hooks:
      - id: isort
        name: isort (python)
        # --- CHANGES START HERE ---
        language: python # Change from system to python
        types: [python]
        additional_dependencies: ["isort==5.12.0"] # Specify the version
        # --- CHANGES END HERE ---

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.43.0 # Use the latest stable version
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$ # Apply only to JS/TS files
        types: [file]
        args: ["--fix", "-c", "frontend/eslint.config.js"]
        # --- CHANGES START HERE ---
        language: node # Change from system to node
        additional_dependencies: # Specify the packages pre-commit should install in its internal node environment
          # Use the versions directly from your frontend/package.json
          - eslint@9.31.0
          - "@babel/core@7.28.0"
          - "@babel/eslint-parser@7.28.0"
          - globals@16.3.0
          - eslint-plugin-react@7.37.5
          - eslint-plugin-react-hooks@5.2.0
          - "metro-react-native-babel-preset@latest"
        # --- CHANGES END HERE ---
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0 # Use the latest stable version
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|md|css|html|yaml)$ # Apply to various file types
        # --- CHANGES START HERE ---
        language: node # Change from system to node
        additional_dependencies:
          - prettier@3.0.0 # Use the specific version you prefer
        # --- CHANGES END HERE ---
