# .github/workflows/frontend-ci.yml
name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Adjust if needed
          cache: 'yarn' # Add this line to cache Yarn dependencies
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: |
          cd frontend
          yarn install # Change from npm install
      - name: Run ESLint
        run: |
          cd frontend
          yarn eslint . # Change from npx eslint . (yarn also supports npx but yarn lint is cleaner)
      - name: Run Prettier check
        run: |
          cd frontend
          yarn prettier --check . # Change from npx prettier --check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Adjust if needed
          cache: 'yarn' # Add this line
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: |
          cd frontend
          yarn install # Change from npm install
      - name: Run Jest tests
        run: |
          cd frontend
          yarn test -- --coverage # Change from npm test -- --coverage

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Adjust if needed
          cache: 'yarn' # Add this line
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: |
          cd frontend
          yarn install # Change from npm install
      - name: Install EAS CLI
        run: yarn global add eas-cli # Change from npm install -g eas-cli
      - name: EAS Build (if configured)
        run: |
          cd frontend
          eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
